name: FCB-Python-autograding

on: [push]

jobs:
  build:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        r-version: [4.1]
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Checking for catalunya_setmanal.csv
        run: if [ -e catalunya_setmanal.csv ] ; then { if [ `md5sum catalunya_setmanal.csv | cut -d ' ' -f 1` == "f8d8df15236eb2c7b861cf035795adff" ] ; then exit 0 ; else { echo WRONG FILE catalunya_setmanal.csv ; exit 1 ; } ; fi } ; else { echo MISSING FILE catalunya_setmanal.csv ; exit 1 ; }
      - name: Check results file COVID19CATlast6months.csv
        run: if [ -e COVID19CATlast6months.csv ] ; then { if [ `md5sum COVID19CATlast6months.csv | cut -d ' ' -f 1` == "8cdd6b70d7cd794ab9dea0b6ab2aaf7f" ] ; then exit 0 ; else { echo CONTENTS IN COVID19CATlast6months.csv ARE WRONG ; exit 1 ; } ; fi ; } ; else { echo MISSING FILE COVID19CATlast6months.csv ; exit 1 ; }
      - name: Checking for syntax errors in analysis.R
        run: Rscript -e "parse('analysis.R')"
      - name: Check for setwd() in analysis.R
        run: nlswd=`grep -n setwd analysis.R | cut -d ':' -f 1` ; if [ $nlswd -gt 0 ] ; then { echo 'YOU ARE CALLING setwd() IN LINE' $nlswd PLEASE DO NOT DO IT. ; exit 1 ; } ; else { exit 0 ; } ; fi
      - name: Run analysis.R
        run: Rscript -e "options(encoding = 'UTF-8') ; source('analysis.R')"
      - name: Check that analysis.R produces the expected results file COVID19CATlast6months.csv
        run: if [ -e COVID19CATlast6months.csv ] ; then { if [ `md5sum COVID19CATlast6months.csv | cut -d ' ' -f 1` == "8cdd6b70d7cd794ab9dea0b6ab2aaf7f" ] ; then exit 0 ; else { echo RESULTING COVID19CATlast6months.csv IS WRONG ; exit 1 ; } ; fi ; } ; else { echo MISSING FILE COVID19CATlast6months.csv ; exit 1 ; }
